package com.disglobal.bnc.tvldecoder.store

import com.disglobal.bnc.tvldecoder.model.EMVTag


class EMVTagStore {

    companion object {

        val emvMap: HashMap<String, EMVTag> = hashMapOf(
            "DF8330" to EMVTag("MIT", false),
            "5F20" to EMVTag("Cardholder Name", true),
            "4F" to EMVTag("Application Identifier", false),
            "5F24" to EMVTag("Application Expiration Date", false),
            "9F16" to EMVTag("Merchant Identifier", true),
            "9F21" to EMVTag("Transaction Time", false),
            "9A" to EMVTag("Transaction Date", false),
            "9F02" to EMVTag("Amount, Authorised (Numeric)", false),
            "9F03" to EMVTag("Amount, Other (Numeric)", false),
            "9F34" to EMVTag("Cardholder Verification Method (CVM) Results", false),
            "9F12" to EMVTag("Application Preferred Name", true),
            "9F06" to EMVTag("Application Identifier (AID) – terminal", false),
            "5F30" to EMVTag("Service Code", false),
            "9F4E" to EMVTag("Merchant Name and git Location", true),
            "5A" to EMVTag("Application Primary Account Number (PAN)", false),
            "57" to EMVTag("Track 2 Equivalent Data", false),
            "9F10" to EMVTag("Issuer Application Data", false),
            "82" to EMVTag("Application Interchange Profile", false),
            "8E" to EMVTag("Cardholder Verification Method (CVM) List", false),
            "5F25" to EMVTag("Application Effective Date", false),
            "9F07" to EMVTag("Application Usage Control", false),
            "9F0D" to EMVTag("Issuer Action Code Default", false),
            "9F0E" to EMVTag("Issuer Action Code Denial", false),
            "9F0F" to EMVTag("Issuer Action Code Online", false),
            "9F26" to EMVTag("Application Cryptogram", false),
            "9F27" to EMVTag("Cryptogram Information Data", false),
            "9F36" to EMVTag(" Application Transaction Counter (ATC)", false),
            "9C" to EMVTag("Transaction Type", false),
            "9F33" to EMVTag("Terminal Capabilities", false),
            "9F37" to EMVTag("Unpredictable Number", false),
            "9F39" to EMVTag("Point-of-Service (POS) Entry Mode", false),
            "9F40" to EMVTag("Additional Terminal Capabilities", false),
            "95" to EMVTag("Terminal Verification Results", false),
            "9B" to EMVTag("Transaction Status Information", false),
            "84" to EMVTag("Dedicated File (DF) Name", false),
            "5F2A" to EMVTag("Transaction Currency Code", false),
            "5F34" to EMVTag("Application Primary Account Number (PAN) Sequence Number", false),
            "9F09" to EMVTag("Application Version Number", false),
            "9F1A" to EMVTag("Terminal Country Code", false),
            "9F1E" to EMVTag("Interface Device (IFD) Serial Number", true),
            "9F35" to EMVTag("Terminal Type", false),
            "9F41" to EMVTag("Transaction Sequence Counter", false),
            "5F28" to EMVTag("Issuer Country Code", false),
            "9F53" to EMVTag("Unknown tag", false),
            "8A" to EMVTag("Application Label", true),
            "50" to EMVTag("Authorisation Response Code", false),
            "9F08" to EMVTag("Application Version Number", false),
            "06" to EMVTag("Object Identifier (OID)", false),
            "41" to EMVTag("Country code and national data", false),
            "42" to EMVTag("Issuer Identification Number (IIN)", false),
            "43" to EMVTag("Card service data", false),
            "44" to EMVTag("Initial access data", false),
            "45" to EMVTag("Card issuer's data", false),
            "46" to EMVTag("Pre-issuing data", false),
            "47" to EMVTag("Card capabilities", false),
            "48" to EMVTag("Status information", false),
            "4D" to EMVTag("Extended header list", false),
            "4F" to EMVTag("Application Identifier (ADF Name)", false),
            "50" to EMVTag("Application Label", false),
            "51" to EMVTag("Path", false),
            "52" to EMVTag("Command to perform", false),
            "53" to EMVTag("Discretionary data, discretionary template", false),
            "56" to EMVTag("Track 1 Data", false),
            "57" to EMVTag("Track 2 Equivalent Data", false),
            "58" to EMVTag("Track 3 Equivalent Data", false),
            "59" to EMVTag("Card expiration date", false),
            "5A" to EMVTag("Application Primary Account Number (PAN)", false),
            "5B" to EMVTag("Name of an individual", false),
            "5C" to EMVTag("Tag list", false),
            "5D" to EMVTag("Deleted (see 9D)", false),
            "5E" to EMVTag("Proprietary login data", false),
            "5F21" to EMVTag("Track 1, identical to the data coded", false),
            "5F22" to EMVTag("Track 2, identical to the data coded", false),
            "5F23" to EMVTag("Track 3, identical to the data coded", false),
            "5F26" to EMVTag("Date, Card Effective", false),
            "5F27" to EMVTag("Interchange control", false),
            "5F29" to EMVTag("Interchange profile", false),
            "5F2B" to EMVTag("Date of birth", false),
            "5F2C" to EMVTag("Cardholder nationality", false),
            "5F2D" to EMVTag("Language Preference", false),
            "5F2E" to EMVTag("Cardholder biometric data", false),
            "5F2F" to EMVTag("PIN usage policy", false),
            "5F32" to EMVTag("Transaction counter", false),
            "5F33" to EMVTag("Date, Transaction", false),
            "5F35" to EMVTag("Sex (ISO 5218)", false),
            "5F36" to EMVTag("Transaction Currency Exponent", false),
            "5F37" to EMVTag("Static internal authentication (one-step)", false),
            "5F38" to EMVTag("Static internal authentication - first associated data", false),
            "5F39" to EMVTag("Static internal authentication - second associated data", false),
            "5F3A" to EMVTag("Dynamic internal authentication", false),
            "5F3B" to EMVTag("Dynamic external authentication", false),
            "5F3C" to EMVTag("Transaction Reference Currency Code", false),
            "5F3D" to EMVTag("Transaction Reference Currency Exponent", false),
            "5F40" to EMVTag("Cardholder portrait image", false),
            "5F41" to EMVTag("Element list", false),
            "5F42" to EMVTag("Address", false),
            "5F43" to EMVTag("Cardholder handwritten signature image", false),
            "5F44" to EMVTag("Application image", false),
            "5F45" to EMVTag("Display message", false),
            "5F46" to EMVTag("Timer", false),
            "5F47" to EMVTag("Message reference", false),
            "5F48" to EMVTag("Cardholder private key", false),
            "5F49" to EMVTag("Cardholder public key", false),
            "5F4A" to EMVTag("Public key of certification authority", false),
            "5F4B" to EMVTag("Deprecated (see note 2 below)", false),
            "5F4C" to EMVTag("Certificate holder authorization", false),
            "5F4D" to EMVTag("Integrated circuit manufacturer identifier", false),
            "5F4E" to EMVTag("Certificate content", false),
            "5F50" to EMVTag("Issuer Uniform resource locator (URL)", false),
            "5F53" to EMVTag("International Bank Account Number (IBAN)", false),
            "5F54" to EMVTag("Bank Identifier Code (BIC)", false),
            "5F55" to EMVTag("Issuer Country Code (alpha2 format)", false),
            "5F56" to EMVTag("Issuer Country Code (alpha3 format)", false),
            "5F57" to EMVTag("Account Type", false),
            "60" to EMVTag("Template, Dynamic Authentication", false),
            "6080" to EMVTag("Commitment (e.g., a positive number less than the public RSA modulus in use)", false),
            "6081" to EMVTag("Challenge (e.g., a number, possibly zero, less than the public RSA exponent in use)", false),
            "6082" to EMVTag("Response (e.g., a positive number less than the public RSA modulus in use)", false),
            "6083" to EMVTag("Committed challenge (e.g., the hash-code of a commitment data object)", false),
            "6084" to EMVTag("Authentication code", false),
            "6085" to EMVTag("Exponential", false),
            "60A0" to EMVTag("Template, Identification data", false),
            "61" to EMVTag("Application Template", false),
            "62" to EMVTag("File Control Parameters (FCP) Template", false),
            "6280" to EMVTag("Number of data bytes in the file, excluding structural information", false),
            "6281" to EMVTag("Number of data bytes in the file, including structural information if any", false),
            "6282" to EMVTag("File descriptor byte", false),
            "6283" to EMVTag("File identifier", false),
            "6284" to EMVTag("DF name", false),
            "6285" to EMVTag("Proprietary information, primitive encoding", false),
            "6286" to EMVTag("Security attribute in proprietary format", false),
            "6287" to EMVTag("Identifier of an EF containing an extension of the file control information", false),
            "6288" to EMVTag("Short EF identifier", false),
            "628A" to EMVTag("Life cycle status byte (LCS)", false),
            "628B" to EMVTag("Security attribute referencing the expanded format", false),
            "628C" to EMVTag("Security attribute in compact format", false),
            "628D" to EMVTag("Identifier of an EF containing security environment templates", false),
            "62A0" to EMVTag("Template, Security attribute for data objects", false),
            "62A1" to EMVTag("Template, Security attribute for physical interfaces", false),
            "62A2" to EMVTag("One or more pairs of data objects, short EF identifier - absolute or relative path", false),
            "62A5" to EMVTag("Proprietary information, constructed encoding", false),
            "62AB" to EMVTag("Security attribute in expanded format", false),
            "62AC" to EMVTag("Identifier of a cryptographic mechanism", false),
            "63" to EMVTag("Wrapper", false),
            "64" to EMVTag("Template, File Management Data (FMD)", false),
            "65" to EMVTag("Cardholder related data", false),
            "66" to EMVTag("Template, Card data", false),
            "67" to EMVTag("Template, Authentication data", false),
            "68" to EMVTag("Special user requirements", false),
            "6A" to EMVTag("Template, Login", false),
            "6A80" to EMVTag("Qualifier", false),
            "6A81" to EMVTag("Telephone Number", false),
            "6A82" to EMVTag("Text", false),
            "6A83" to EMVTag("Delay indicators, for detecting an end of message", false),
            "6A84" to EMVTag("Delay indicators, for detecting an absence of response", false),
            "6B" to EMVTag("Template, Qualified name", false),
            "6B06" to EMVTag("Qualified name", false),
            "6B80" to EMVTag("Name", false),
            "6BA0" to EMVTag("Name", false),
            "6C" to EMVTag("Template, Cardholder image", false),
            "6D" to EMVTag("Template, Application image", false),
            "6E" to EMVTag("Application related data", false),
            "6F" to EMVTag("File Control Information (FCI) Template", false),
            "6FA5" to EMVTag("Template, FCI A5", false),
            "70" to EMVTag("READ RECORD Response Message Template", false),
            "71" to EMVTag("Issuer Script Template 1", false),
            "7186" to EMVTag("Issuer Script Command", false),
            "719F18" to EMVTag("Issuer Script Identifier", false),
            "72" to EMVTag("Issuer Script Template 2", false),
            "73" to EMVTag("Directory Discretionary Template", false),
            "77" to EMVTag("Response Message Template Format 2", false),
            "78" to EMVTag("Compatible Tag Allocation Authority", false),
            "79" to EMVTag("Coexistent Tag Allocation Authority", false),
            "7A" to EMVTag("Template, Security Support (SS)", false),
            "7A80" to EMVTag("Card session counter", false),
            "7A81" to EMVTag("Session identifier", false),
            "7A82" to EMVTag("File selection counter", false),
            "7A83" to EMVTag("File selection counter", false),
            "7A84" to EMVTag("File selection counter", false),
            "7A85" to EMVTag("File selection counter", false),
            "7A86" to EMVTag("File selection counter", false),
            "7A87" to EMVTag("File selection counter", false),
            "7A88" to EMVTag("File selection counter", false),
            "7A89" to EMVTag("File selection counter", false),
            "7A8A" to EMVTag("File selection counter", false),
            "7A8B" to EMVTag("File selection counter", false),
            "7A8C" to EMVTag("File selection counter", false),
            "7A8D" to EMVTag("File selection counter", false),
            "7A8E" to EMVTag("File selection counter", false),
            "7A93" to EMVTag("Digital signature counter", false),
            "7A9F2X" to EMVTag("Internal progression value", false),
            "7A9F3Y" to EMVTag("External progression value", false),
            "7B" to EMVTag("Template, Security Environment (SE)", false),
            "7B80" to EMVTag("SEID byte, mandatory", false),
            "7B8A" to EMVTag("LCS byte, optional", false),
            "7BAC" to EMVTag("Cryptographic mechanism identifier template, optional", false),
            "7BA4" to EMVTag("Control reference template (CRT)", false),
            "7BAA" to EMVTag("Control reference template (CRT)", false),
            "7BB4" to EMVTag("Control reference template (CRT)", false),
            "7BB6" to EMVTag("Control reference template (CRT)", false),
            "7BB8" to EMVTag("Control reference template (CRT)", false),
            "7D" to EMVTag("Template, Secure Messaging (SM)", false),
            "7D80" to EMVTag("Plain value not coded in BER-TLV", false),
            "7D81" to EMVTag("Plain value not coded in BER-TLV", false),
            "7D82" to EMVTag("Cryptogram", false),
            "7D83" to EMVTag("Cryptogram", false),
            "7D84" to EMVTag("Cryptogram", false),
            "7D85" to EMVTag("Cryptogram", false),
            "7D86" to EMVTag("Padding-content indicator byte followed by cryptogram", false),
            "7D87" to EMVTag("Padding-content indicator byte followed by cryptogram", false),
            "7D8E" to EMVTag("Cryptographic checksum", false),
            "7D90" to EMVTag("Hash-code", false),
            "7D91" to EMVTag("Hash-code", false),
            "7D92" to EMVTag("Certificate", false),
            "7D93" to EMVTag("Certificate", false),
            "7D94" to EMVTag("Security environment identifier", false),
            "7D95" to EMVTag("Security environment identifier", false),
            "7D96" to EMVTag("Number Le in the unsecured command APDU", false),
            "7D97" to EMVTag("Number Le in the unsecured command APDU", false),
            "7D99" to EMVTag("Processing status of the secured response APDU", false),
            "7D9A" to EMVTag("Input data element for the computation of a digital signature", false),
            "7D9B" to EMVTag("Input data element for the computation of a digital signature", false),
            "7D9C" to EMVTag("Public key", false),
            "7D9D" to EMVTag("Public key", false),
            "7D9E" to EMVTag("Digital signature", false),
            "7DA0" to EMVTag("Input template for the computation of a hash-code", false),
            "7DA1" to EMVTag("Input template for the computation of a hash-code", false),
            "7DA2" to EMVTag("Input template for the verification of a cryptographic checksum", false),
            "7DA4" to EMVTag("Control reference template for authentication", false),
            "7DA5" to EMVTag("Control reference template for authentication", false),
            "7DA8" to EMVTag("Input template for the verification of a digital signature", false),
            "7DAA" to EMVTag("Template, Control reference for hash-code", false),
            "7DAB" to EMVTag("Template, Control reference for hash-code", false),
            "7DAC" to EMVTag("Input template for the computation of a digital signature", false),
            "7DAD" to EMVTag("Input template for the computation of a digital signature", false),
            "7DAE" to EMVTag("Input template for the computation of a certificate", false),
            "7DAF" to EMVTag("Input template for the computation of a certificate", false),
            "7DB0" to EMVTag("Plain value coded in BER-TLV and including secure messaging data objects", false),
            "7DB1" to EMVTag("Plain value coded in BER-TLV and including secure messaging data objects", false),
            "7DB2" to EMVTag("Plain value coded in BER-TLV, but not including secure messaging data objects", false),
            "7DB3" to EMVTag("Plain value coded in BER-TLV, but not including secure messaging data objects", false),
            "7DB4" to EMVTag("Control reference template for cryptographic checksum", false),
            "7DB5" to EMVTag("Control reference template for cryptographic checksum", false),
            "7DB6" to EMVTag("Control reference template for digital signature", false),
            "7DB7" to EMVTag("Control reference template for digital signature", false),
            "7DB8" to EMVTag("Control reference template for confidentiality (CT)", false),
            "7DB9" to EMVTag("Control reference template for confidentiality (CT)", false),
            "7DBA" to EMVTag("Response descriptor template", false),
            "7DBB" to EMVTag("Response descriptor template", false),
            "7DBC" to EMVTag("Input template for the computation of a digital signature (the template is signed)", false),
            "7DBD" to EMVTag("Input template for the computation of a digital signature (the template is signed)", false),
            "7DBE" to EMVTag("Input template for the verification of a certificate (the template is certified)", false),
            "7E" to EMVTag("Template, Nesting Interindustry data objects", false),
            "7F20" to EMVTag("Display control template", false),
            "7F21" to EMVTag("Cardholder certificate", false),
            "7F2E" to EMVTag("Biometric data template", false),
            "7F49" to EMVTag("Template, Cardholder public key", false),
            "7F4980" to EMVTag("Algorithm reference as used in control reference data objects for secure messaging", false),
            "7F4981" to EMVTag("RSA Modulus, or DSA First prime, or ECDSA Prime", false),
            "7F4982" to EMVTag("RSA Public exponent, or DSA Second prime, or ECDSA First coefficient", false),
            "7F4983" to EMVTag("DSA Basis, or ECDSA Second coefficient", false),
            "7F4984" to EMVTag("DSA Public key, or ECDSA Generator", false),
            "7F4985" to EMVTag("ECDSA Order", false),
            "7F4986" to EMVTag("ECDSA Public key", false),
            "7F4C" to EMVTag("Template, Certificate Holder Authorization", false),
            "7F4E" to EMVTag("Certificate Body", false),
            "7F4E42" to EMVTag("Certificate Authority Reference", false),
            "7F4E5F20" to EMVTag("Certificate Holder Reference", false),
            "7F4E5F24" to EMVTag("Expiration Date, Certificate", false),
            "7F4E5F25" to EMVTag("Effective Date, Certificate", false),
            "7F4E5F29" to EMVTag("Certificate Profile Identifier", false),
            "7F4E65" to EMVTag("Certificate Extensions", false),
            "7F60" to EMVTag("Template, Biometric information", false),
            "80" to EMVTag("Response Message Template Format 1", false),
            "81" to EMVTag("Amount, Authorised (Binary)", false),
            "82" to EMVTag("Application Interchange Profile (AIP)", false),
            "83" to EMVTag("Command Template", false),
            "84" to EMVTag("Dedicated File (DF) Name", false),
            "86" to EMVTag("Issuer Script Command", false),
            "87" to EMVTag("Application Priority Indicator", false),
            "88" to EMVTag("Short File Identifier (SFI)", false),
            "89" to EMVTag("Authorisation Code", false),
            "8A" to EMVTag("Authorisation Response Code (ARC)", false),
            "8C" to EMVTag("Card Risk Management Data Object List 1 (CDOL1)", false),
            "8D" to EMVTag("Card Risk Management Data Object List 2 (CDOL2)", false),
            "8E" to EMVTag("Cardholder Verification Method (CVM) List", false),
            "8F" to EMVTag("Certification Authority Public Key Index (PKI)", false),
            "90" to EMVTag("Issuer Public Key Certificate", false),
            "91" to EMVTag("Issuer Authentication Data", false),
            "92" to EMVTag("Issuer Public Key Remainder", false),
            "93" to EMVTag("Signed Static Application Data (SAD)", false),
            "94" to EMVTag("Application File Locator (AFL)", false),
            "95" to EMVTag("Terminal Verification Results (TVR)", false),
            "97" to EMVTag("Transaction Certificate Data Object List (TDOL)", false),
            "98" to EMVTag("Transaction Certificate (TC) Hash Value", false),
            "99" to EMVTag("Transaction Personal Identification Number (PIN) Data", false),
            "9A" to EMVTag("Transaction Date", false),
            "9B" to EMVTag("Transaction Status Information (TSI)", false),
            "9C" to EMVTag("Transaction Type", false),
            "9D" to EMVTag("Directory Definition File (DDF) Name", false),
            "9F01" to EMVTag("Acquirer Identifier", false),
            "9F02" to EMVTag("Amount, Authorised (Numeric)", false),
            "9F03" to EMVTag("Amount, Other (Numeric)", false),
            "9F04" to EMVTag("Amount, Other (Binary)", false),
            "9F05" to EMVTag("Application Discretionary Data", false),
            "9F06" to EMVTag("Application Identifier (AID), Terminal", false),
            "9F07" to EMVTag("Application Usage Control (AUC)", false),
            "9F08" to EMVTag("Application Version Number", false),
            "9F09" to EMVTag("Application Version Number", false),
            "9F0B" to EMVTag("Cardholder Name - Extended", false),
            "9F0D" to EMVTag("Issuer Action Code - Default", false),
            "9F0E" to EMVTag("Issuer Action Code - Denial", false),
            "9F0F" to EMVTag("Issuer Action Code - Online", false),
            "9F10" to EMVTag("Issuer Application Data (IAD)", false),
            "9F11" to EMVTag("Issuer Code Table Index", false),
            "9F12" to EMVTag("Application Preferred Name", false),
            "9F13" to EMVTag("Last Online Application Transaction Counter (ATC) Register", false),
            "9F14" to EMVTag("Lower Consecutive Offline Limit (LCOL)", false),
            "9F15" to EMVTag("Merchant Category Code (MCC)", false),
            "9F16" to EMVTag("Merchant Identifier", false),
            "9F17" to EMVTag("Personal Identification Number (PIN) Try Counter", false),
            "9F18" to EMVTag("Issuer Script Identifier", false),
            "9F19" to EMVTag("Deleted (see 9F49)", false),
            "9F1A" to EMVTag("Terminal Country Code", false),
            "9F1B" to EMVTag("Terminal Floor Limit", false),
            "9F1C" to EMVTag("Terminal Identification", false),
            "9F1D" to EMVTag("Terminal Risk Management Data", false),
            "9F1E" to EMVTag("Interface Device (IFD) Serial Number", false),
            "9F1F" to EMVTag("Track 1 Discretionary Data", false),
            "9F20" to EMVTag("Track 2 Discretionary Data", false),
            "9F21" to EMVTag("Transaction Time", false),
            "9F22" to EMVTag("Certification Authority Public Key Index (PKI)", false),
            "9F23" to EMVTag("Upper Consecutive Offline Limit (UCOL)", false),
            "9F24" to EMVTag("Payment Account Reference (PAR)", false),
            "9F26" to EMVTag("Application Cryptogram (AC)", false),
            "9F27" to EMVTag("Cryptogram Information Data (CID)", false),
            "9F29" to EMVTag("Extended Selection", false),
            "9F2A" to EMVTag("Kernel Identifier", false),
            "9F2D" to EMVTag("ICC PIN Encipherment Public Key Certificate", false),
            "9F2E" to EMVTag("ICC PIN Encipherment Public Key Exponent", false),
            "9F2F" to EMVTag("ICC PIN Encipherment Public Key Remainder", false),
            "9F32" to EMVTag("Issuer Public Key Exponent", false),
            "9F33" to EMVTag("Terminal Capabilities", false),
            "9F34" to EMVTag("Cardholder Verification Method (CVM) Results", false),
            "9F35" to EMVTag("Terminal Type", false),
            "9F36" to EMVTag("Application Transaction Counter (ATC)", false),
            "9F37" to EMVTag("Unpredictable Number (UN)", false),
            "9F38" to EMVTag("Processing Options Data Object List (PDOL)", false),
            "9F39" to EMVTag("Point-of-Service (POS) Entry Mode", false),
            "9F3A" to EMVTag("Amount, Reference Currency (Binary)", false),
            "9F3B" to EMVTag("Currency Code, Application Reference", false),
            "9F3C" to EMVTag("Currency Code, Transaction Reference", false),
            "9F3D" to EMVTag("Currency Exponent, Transaction Reference", false),
            "9F40" to EMVTag("Additional Terminal Capabilities (ATC)", false),
            "9F41" to EMVTag("Transaction Sequence Counter", false),
            "9F42" to EMVTag("Currency Code, Application", false),
            "9F43" to EMVTag("Currency Exponent, Application Reference", false),
            "9F44" to EMVTag("Currency Exponent, Application", false),
            "9F45" to EMVTag("Data Authentication Code", false),
            "9F46" to EMVTag("ICC Public Key Certificate", false),
            "9F47" to EMVTag("ICC Public Key Exponent", false),
            "9F48" to EMVTag("ICC Public Key Remainder", false),
            "9F49" to EMVTag("Dynamic Data Authentication Data Object List (DDOL)", false),
            "9F4A" to EMVTag("Static Data Authentication Tag List (SDA)", false),
            "9F4B" to EMVTag("Signed Dynamic Application Data (SDAD)", false),
            "9F4C" to EMVTag("ICC Dynamic Number", false),
            "9F4D" to EMVTag("Log Entry", false),
            "9F4E" to EMVTag("Merchant Name and Location", false),
            "9F4F" to EMVTag("Log Format", false),
            "9F50" to EMVTag("Offline Accumulator Balance", false),
            "9F51" to EMVTag("Application Currency Code", false),
            "9F52" to EMVTag("Application Default Action (ADA)", false),
            "9F53" to EMVTag("Consecutive Transaction Counter International Limit (CTCIL)", false),
            "9F54" to EMVTag("Cumulative Total Transaction Amount Limit (CTTAL)", false),
            "9F55" to EMVTag("Geographic Indicator", false),
            "9F56" to EMVTag("Issuer Authentication Indicator", false),
            "9F57" to EMVTag("Issuer Country Code", false),
            "9F58" to EMVTag("Consecutive Transaction Counter Limit (CTCL)", false),
            "9F59" to EMVTag("Consecutive Transaction Counter Upper Limit (CTCUL)", false),
            "9F5A" to EMVTag("Application Program Identifier (Program ID)", false),
            "9F5B" to EMVTag("Issuer Script Results", false),
            "9F5C" to EMVTag("Cumulative Total Transaction Amount Upper Limit (CTTAUL)", false),
            "9F5D" to EMVTag("Available Offline Spending Amount (AOSA)", false),
            "9F5E" to EMVTag("Consecutive Transaction International Upper Limit (CTIUL)", false),
            "9F5F" to EMVTag("DS Slot Availability", false),
            "9F60" to EMVTag("CVC3 (Track1)", false),
            "9F61" to EMVTag("CVC3 (Track2)", false),
            "9F62" to EMVTag("PCVC3 (Track1)", false),
            "9F63" to EMVTag("Offline Counter Initial Value", false),
            "9F64" to EMVTag("NATC (Track1)", false),
            "9F65" to EMVTag("PCVC3 (Track2)", false),
            "9F66" to EMVTag("Terminal Transaction Qualifiers (TTQ)", false),
            "9F67" to EMVTag("MSD Offset", false),
            "9F68" to EMVTag("Card Additional Processes", false),
            "9F69" to EMVTag("Card Authentication Related Data", false),
            "9F6A" to EMVTag("Unpredictable Number (Numeric)", false),
            "9F6B" to EMVTag("Card CVM Limit", false),
            "9F6C" to EMVTag("Card Transaction Qualifiers (CTQ)", false),
            "9F6D" to EMVTag("VLP Reset Threshold", false),
            "9F6E" to EMVTag("Third Party Data", false),
            "9F6F" to EMVTag("DS Slot Management Control", false),
            "9F70" to EMVTag("Protected Data Envelope 1", false),
            "9F71" to EMVTag("Protected Data Envelope 2", false),
            "9F72" to EMVTag("Protected Data Envelope 3", false),
            "9F73" to EMVTag("Protected Data Envelope 4", false),
            "9F74" to EMVTag("Protected Data Envelope 5", false),
            "9F75" to EMVTag("Unprotected Data Envelope 1", false),
            "9F76" to EMVTag("Unprotected Data Envelope 2", false),
            "9F77" to EMVTag("Unprotected Data Envelope 3", false),
            "9F78" to EMVTag("Unprotected Data Envelope 4", false),
            "9F79" to EMVTag("Unprotected Data Envelope 5", false),
            "9F7A" to EMVTag("VLP Terminal Support Indicator", false),
            "9F7B" to EMVTag("VLP Terminal Transaction Limit", false),
            "9F7C" to EMVTag("Customer Exclusive Data (CED)", false),
            "9F7D" to EMVTag("DS Summary 1", false),
            "9F7E" to EMVTag("Mobile Support Indicator", false),
            "9F7F" to EMVTag("DS Unpredictable Number", false),
            "A5" to EMVTag("File Control Information (FCI) Proprietary Template", false),
            "BF0C" to EMVTag("File Control Information (FCI) Issuer Discretionary Data", false),
            "BF50" to EMVTag("Visa Fleet - CDO", false),
            "BF60" to EMVTag("Integrated Data Storage Record Update Template", false),
            "C3" to EMVTag("Card issuer action code -decline", false),
            "C4" to EMVTag("Card issuer action code -default", false),
            "C5" to EMVTag("Card issuer action code online", false),
            "C6" to EMVTag("PIN Try Limit", false),
            "C7" to EMVTag("CDOL 1 Related Data Length", false),
            "C8" to EMVTag("Card risk management country code", false),
            "C9" to EMVTag("Card risk management currency code", false),
            "CA" to EMVTag("Lower cumulative offline transaction amount", false),
            "CB" to EMVTag("Upper cumulative offline transaction amount", false),
            "CD" to EMVTag("Card Issuer Action Code (PayPass) - Default", false),
            "CE" to EMVTag("Card Issuer Action Code (PayPass) - Online", false),
            "CF" to EMVTag("Card Issuer Action Code (PayPass) - Decline", false),
            "D1" to EMVTag("Currency conversion table", false),
            "D2" to EMVTag("Integrated Data Storage Directory (IDSD)", false),
            "D3" to EMVTag("Additional check table", false),
            "D5" to EMVTag("Application Control", false),
            "D6" to EMVTag("Default ARPC response code", false),
            "D7" to EMVTag("Application Control (PayPass)", false),
            "D8" to EMVTag("AIP (PayPass)", false),
            "D9" to EMVTag("AFL (PayPass)", false),
            "DA" to EMVTag("Static CVC3-TRACK1", false),
            "DB" to EMVTag("Static CVC3-TRACK2", false),
            "DC" to EMVTag("IVCVC3-TRACK1", false),
            "DD" to EMVTag("IVCVC3-TRACK2", false),
            "DF01" to EMVTag("Encrypted PIN Block in Tag 9F62 - ISO 95641 Format 0", false),
            "DF02" to EMVTag("PEK Version Number", false),
            "DF03" to EMVTag("PIN Try Limit", false),
            "DF04" to EMVTag("PIN Try Counter (VSDC Application)", false),
            "DF05" to EMVTag("AIP - For VISA Contactless", false),
            "DF06" to EMVTag("Products permitted", false),
            "DF07" to EMVTag("Offline checks mandated", false),
            "DF08" to EMVTag("UDKmac", false),
            "DF09" to EMVTag("UDKenc", false),
            "DF0B" to EMVTag("Retries Permitted Limit", false),
            "DF0C" to EMVTag("Script Message Update", false),
            "DF0D" to EMVTag("Fleet Issuer Action Code - Default", false),
            "DF0E" to EMVTag("Fleet Issuer Action Code - Denial", false),
            "DF0F" to EMVTag("Fleet Issuer Action Code - Online", false),
            "DF12" to EMVTag("Vehicle Registration Number", false),
            "DF13" to EMVTag("DDA Public Modulus", false),
            "DF14" to EMVTag("Driver Name", false),
            "DF15" to EMVTag("Driver ID", false),
            "DF16" to EMVTag("Max Fill Volume", false),
            "DF17" to EMVTag("DDA Public Modulus Length", false),
            "DF18" to EMVTag("Mileage", false),
            "DF20" to EMVTag("Issuer Proprietary Bitmap (IPB)", false),
            "DF21" to EMVTag("Internet Authentication Flag (IAF)", false),
            "DF22" to EMVTag("Encrypted PEK - RFU", false),
            "DF23" to EMVTag("PEK Key Check Value - RFU", false),
            "DF24" to EMVTag("MDK - Key derivation Index", false),
            "DF25" to EMVTag("VISA DPA - MDK - Key derivation Index", false),
            "DF26" to EMVTag("Encrypted PIN Block - ISO 9564-1 Format 1 PIN Block (Thales P3 Format 05)", false),
            "DF40" to EMVTag("qVSDC AIP", false),
            "DF41" to EMVTag("VSDC AIP", false),
            "DF42" to EMVTag("UDKac", false),
            "DF43" to EMVTag("UDKmac", false),
            "DF44" to EMVTag("UDKenc", false),
            "DF47" to EMVTag("UDKcvc", false),
            "DF48" to EMVTag("UDKac KCV", false),
            "DF49" to EMVTag("UDKmac KCV", false),
            "DF4A" to EMVTag("UDKenc KCV", false),
            "DF4B" to EMVTag("UDKcvc KCV", false),
            "DF51" to EMVTag("Grand Parent AC", false),
            "DF52" to EMVTag("Parent AC", false),
            "DF53" to EMVTag("Grand Parent MAC", false),
            "DF54" to EMVTag("Parent MAC", false),
            "DF55" to EMVTag("Grand Parent ENC", false),
            "DF56" to EMVTag("Parent ENC/Terminal Action Code - Default", false),
            "DF57" to EMVTag("Terminal Action Code - Decline", false),
            "DF60" to EMVTag("DS Input (Card)", false),
            "DF61" to EMVTag("DDA Component Q", false),
            "DF62" to EMVTag("DS ODS Info", false),
            "DF63" to EMVTag("DDA Component D2", false),
            "DF64" to EMVTag("DDA Component Q Minus 1 Mod P", false),
            "DF65" to EMVTag("DDA Private Exponent", false),
            "DF6B" to EMVTag("Paypass Contactless", false),
            "DF79" to EMVTag("Dynamic Data Authentication Keys", false),
            "DF8101" to EMVTag("DS Summary 2", false),
            "DF8102" to EMVTag("DS Summary 3", false),
            "DF8104" to EMVTag("Balance Read Before Gen AC", false),
            "DF8105" to EMVTag("Balance Read After Gen AC", false),
            "DF8106" to EMVTag("Data Needed", false),
            "DF8107" to EMVTag("CDOL1 Related Data", false),
            "DF8108" to EMVTag("DS AC Type", false),
            "DF8109" to EMVTag("DS Input (Term)", false),
            "DF810A" to EMVTag("DS ODS Info For Reader", false),
            "DF810B" to EMVTag("DS Summary Status", false),
            "DF810C" to EMVTag("Kernel ID", false),
            "DF810D" to EMVTag("DSVN Term", false),
            "DF810E" to EMVTag("Post-Gen AC Put Data Status", false),
            "DF810F" to EMVTag("Pre-Gen AC Put Data Status", false),
            "DF8110" to EMVTag("Proceed To First Write Flag", false),
            "DF8111" to EMVTag("PDOL Related Data", false),
            "DF8112" to EMVTag("Tags To Read", false),
            "DF8113" to EMVTag("DRDOL Related Data", false),
            "DF8114" to EMVTag("Reference Control Parameter", false),
            "DF8115" to EMVTag("Error Indication", false),
            "DF8116" to EMVTag("User Interface Request Data", false),
            "DF8117" to EMVTag("Card Data Input Capability", false),
            "DF8118" to EMVTag("CVM Capability - CVM Required", false),
            "DF8119" to EMVTag("CVM Capability - No CVM Required", false),
            "DF811A" to EMVTag("Default UDOL", false),
            "DF811B" to EMVTag("Kernel Configuration", false),
            "DF811C" to EMVTag("Max Lifetime of Torn Transaction Log Record", false),
            "DF811D" to EMVTag("Max Number of Torn Transaction Log Records", false),
            "DF811E" to EMVTag("Mag-stripe CVM Capability - CVM Required", false),
            "DF811F" to EMVTag("Security Capability", false),
            "DF8120" to EMVTag("Terminal Action Code - Default", false),
            "DF8121" to EMVTag("Terminal Action Code - Denial", false),
            "DF8122" to EMVTag("Terminal Action Code - Online", false),
            "DF8123" to EMVTag("Reader Contactless Floor Limit", false),
            "DF8124" to EMVTag("Reader Contactless Transaction Limit (No On-device CVM)", false),
            "DF8125" to EMVTag("Reader Contactless Transaction Limit (On-device CVM)", false),
            "DF8126" to EMVTag("Reader CVM Required Limit", false),
            "DF8127" to EMVTag("Time Out Value", false),
            "DF8128" to EMVTag("IDS Status", false),
            "DF8129" to EMVTag("Outcome Parameter Set", false),
            "DF812A" to EMVTag("DD Card (Track1)", false),
            "DF812B" to EMVTag("DD Card (Track2)", false),
            "DF812C" to EMVTag("Mag-stripe CVM Capability - No CVM Required", false),
            "DF812D" to EMVTag("Message Hold Time", false),
            "DF8130" to EMVTag("Hold Time Value", false),
            "DF8131" to EMVTag("Phone Message Table", false),
            "FF60" to EMVTag("Visa International", false),
            "FF62" to EMVTag("Visa Magnetic Stripe", false),
            "FF63" to EMVTag("Visa Quick VSDC", false),
            "FF8101" to EMVTag("Torn Record", false),
            "FF8102" to EMVTag("Tags To Write Before Gen AC", false),
            "FF8103" to EMVTag("Tags To Write After Gen AC", false),
            "FF8104" to EMVTag("Data To Send", false),
            "FF8105" to EMVTag("Data Record", false),
            "FF8106" to EMVTag("Discretionary Data", false),
            "C0" to EMVTag("KSN (Data encryption Key)", false),
            "C1" to EMVTag("KSN (PIN encryption Key)", false),
            "C2" to EMVTag("Encrypted Data", false),
            "C4" to EMVTag("Masked PAN", false),
            "C5" to EMVTag("Encrypted Batch data", false),
            "C6" to EMVTag("Encrypted Reversal data", false),
            "C7" to EMVTag("KSN (Track Key)", false),
            "C8" to EMVTag("Encrypted Track", false),
            "C9" to EMVTag("Encryption PAN", false),
            "DF2D" to EMVTag("Merchant Phone Number", false),
            "DF8330" to EMVTag("Message Type", false),
            "DF8331" to EMVTag("Retrieval Reference Number", false),
            "DF8332" to EMVTag("Batch Number", false),
            "DF8333" to EMVTag("System Trace Audit", false),
            "DF8334" to EMVTag("Invoice Number", false),
            "8A" to EMVTag("Authentication Response Code", false),
            "9F16" to EMVTag("Merchant ID", false),
            "9F1C" to EMVTag("Terminal Identification", false),
            "9F41" to EMVTag("Transaction Sequence Counter", false),
            "DF832A" to EMVTag("Receipt", false),
            "DF8330" to EMVTag("MIT", false),
            "DF8331" to EMVTag("Retrieval Reference Number (If approved)", false),
            "DF8332" to EMVTag("Batch Number", false),
            "DF8333" to EMVTag("STAN", false),
            "DF8334" to EMVTag("Invoice Number (Recibo)", false),
            "DF8340" to EMVTag("Modo de conexión", false),
            "DF8344" to EMVTag("RIF del comercio", false),
            "DF8345" to EMVTag("Auth Code", false),
            "DF8346" to EMVTag("Date (ddmmyyyy) DE060", false),
            "DF8347" to EMVTag("Nuevo lote", false),
            "DF8348" to EMVTag("WK", false),
            "DF8349" to EMVTag("CVM limit", false),
            "DF834A" to EMVTag("Contactless limit", false),
            "DF834B" to EMVTag("Invoice Number (Factura)", false),
            "DF834C" to EMVTag("ID empresa", false),
            "DF8350" to EMVTag("Auth Code (HEX)", false),
            "DF836A" to EMVTag("CVV (card swipe)", false),
            "DF836B" to EMVTag("Client id (Cedula)", false),
            "DF836C" to EMVTag("Account type (Debit cards)", false),
            "DF836D" to EMVTag("Last four digits (card swipe)", false),
            "DF836E" to EMVTag("Service code", false),
            "DF836F" to EMVTag("Client service identifier", false)
        )
    }

}